"""add user_id to facturas

Revision ID: 002
Revises: 001
Create Date: 2026-03-30 12:01:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the column as nullable to avoid issues with existing rows
    op.add_column('facturas', sa.Column('user_id', sa.UUID(), nullable=True))

    # Create foreign key constraint
    op.create_foreign_key(
        'fk_facturas_user_id',
        'facturas',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # Create index for efficient queries
    op.create_index(
        'idx_facturas_user_id_created_at',
        'facturas',
        ['user_id', 'created_at']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_facturas_user_id_created_at', table_name='facturas')
    op.drop_constraint('fk_facturas_user_id', 'facturas', type_='foreignkey')
    op.drop_column('facturas', 'user_id')
    # ### end Alembic commands ###
